log:
  level: debug
http:
  bind_address: 127.0.0.1:3000
source:
  kind: WebFolder
  web_folder:
    base_url: https://example.com
  path_prefix: /assets
  network:
    config:
      timeout: 5s
handler:
  response:
    cache_duration: 10m
